window.WA_DATA = {
  me: { name: "Daniel Vorcaro", avatar: "assets/avatars/vorcaro.jpg" },
  chats: [
    {
      id: "moraes",
      name: "Alexandre de Moraes BRASILIA",
      phone: "+55 61 99266-4093",
      avatar: "assets/avatars/moraes.jpg",
      tags: ["moraes"],
      messages: [
        { type: "system", date: "2025-09-17", time: "22:41", text: "As mensagens e chamadas desta conversa estão protegidas com a criptografia de ponta a ponta. Toque para mais informações." },
        { type: "system", date: "2025-09-17", time: "22:41", text: "Alexandre de Moraes BRASILIA usa uma duração padrão para mensagens temporárias em novas conversas. Todas as mensagens desaparecerão desta conversa após 24 horas." },
        { type: "day", date: "2025-10-01" },
        { dir: "in", type: "deleted", time: "22:17", text: "Mensagem apagada pelo remetente" },
        { dir: "in", type: "deleted", time: "22:17", text: "Mensagem apagada pelo remetente" },
        { dir: "in", type: "deleted", time: "22:17", text: "Mensagem apagada pelo remetente" },
        { dir: "in", type: "deleted", time: "22:18", text: "Mensagem apagada pelo remetente" },
        { type: "day", date: "2025-10-30" },
        { dir: "out", type: "note", time: "13:33", title: "Nota", text: "Boa, vou mudar minha ida a abu dhabi pra conseguir te ver, se voce puder na terça feira!\n\nAs coisas aqui do ponto de vista economico estao andando bem. Consegui colocar no banco 800mm ja e devem entrar mais 400mm proxima semana.\nE FGC começou a fazer aos poucos.\n\nO problema agora é que tive informações informais e em confidencia de turma do banco central, que G e os diretores estao na pressao maxima de novo pra uma medida, pois o bacen esta sendo muito pressionado pela PF e MP, alegando que farao algo contra mim. É importante reforçar com Andrei e Paulo pra nao deixar ninguem de baixo fazer uma sacanagem que ai vai tudo pro saco.\nEstou disponivel pra tratar e explicar qq coisa, so nao pode ter sacanagem. Vou te mandar os nomes que tem ido ao Bacen alegando que farao algo em breve" },
        { dir: "out", type: "note", time: "13:38", title: "Nota", text: "Pf Dennis cali Wilker / guilherme - sp Janaina - brasilia daniel de brito Mp - ubiratan Gabriel pimenta Guilherme" },
        { dir: "out", type: "note", time: "13:44", title: "Nota", text: "De pessoas de dentro do bacen que sao meus amigos e ficaram preocupados. Eles participaram das reunioes, por isso info 100%. Eu só nao posso queima los, pq tinham poucas pessoas, e saberao que eles me falaram, se isso chegar no G. Entao temos so que ter cuidado de como conduzir com o G depois." },
        { type: "day", date: "2025-11-17" },
        { dir: "out", type: "note", time: "07:19", title: "Nota", text: "Bom dia tudo bem?\n\nEstou tentando antecipar os investidores aqui, e tenho chances de conseguir assinar e anunciar ainda hoje uma parte. E ai eu irei pra la pra tentar assinatura dos demais investidores estrangeiros.\n\nDe um outro lado, acho que o tema que falamos começou a dar uma vazada, obviamente sem qualquer detalhes. Mas a turma do brb me disse que ta tendo um movimento de sacanagem do caso. E que a mesma jornalista de antes estava fazendo perguntas la. Se vazar algo sera pessimo mas pode ser um gancho pra entrar no circuito do processo.\n\nSe tiver alguma novidade vamos falar." },
        { dir: "out", type: "note", time: "17:22", title: "Nota", text: "Fiz uma correria aqui pra tentar salvar.\nFiz o que deu, vou anunciar parte da transação" },
        { dir: "out", type: "note", time: "17:26", title: "Nota", text: "Alguma novidade? Conseguiu ter noticia ou bloquear?" },
        { dir: "out", type: "note", time: "20:04", title: "Nota", text: "Alguma novidade?" },
        { dir: "out", type: "note", time: "20:48", title: "Nota", text: "Foi. Seria melhor na sexta junto com os gringos mas foi o que deu pra fazer dentro da situação. Acho que pode inibir.\nAmanha comecam as batidas do esteves.\nTo indo assinar com os investidores de fora e estou online." }
      ]
    },
    {
      id: "faria",
      name: "Fábio Faria",
      phone: "556199910111",
      avatar: "assets/avatars/faria.jpg",
      tags: ["moraes", "contrato", "londres"],
      messages: [
        { type: "day", date: "2023-12-21" },
        { dir: "out", type: "text", time: "09:33", text: "Ok" },
        { dir: "in", type: "text", time: "09:55", text: "Me passe seu carro e placa e o carro dele também para eu autorizar a segurança a acompanhar na garagem" },
        { dir: "out", type: "text", time: "10:42", text: "Chego 11 cravado?" },
        { dir: "out", type: "text", time: "10:42", text: "Ja passo" },
        { dir: "out", type: "text", time: "10:44", text: "Range Rover Vogue\nRSB7C37" },
        { dir: "in", type: "text", time: "10:45", text: "Isso" },
        { dir: "in", type: "audio", time: "16:12", duration: "0:50", transcript: "Fala, irmão, tudo bem? Quando saímos de lá, ele perguntou se eu tava sozinho, ele me ligou. Aí perguntou, mais ou menos, o que eu achava. Eu falei: “Cara, fica livre aí, dentro do que ele falou”, e tal. Ele falou: “Pô, gostei da conversa. Vou montar um negócio bacana demais e, já logo na terça-feira, eu quero marcar.” Então, eu te ligo aí pra ver o horário, pra vocês voltarem aqui na terça, tá bom? Então, tudo certo. Foi bom demais. E vamos ver se amanhã a gente encontra algum horário. Eu queria ver se conseguia ir lá no prédio, lá, naquele que você falou. Tô livre geral. Só tenho um almoço com o Alexandre no CADE, meio-dia. Tô livre antes e depois. De repente, se você não conseguir, não. É só liberar lá para eu ir. Não tenho nada para fazer, tá? Estou mais tranquilo. Me avisa aí. Um abraço. Valeu." },
        { dir: "out", type: "text", time: "16:57", text: "Boa" },
        { dir: "out", type: "text", time: "16:57", text: "Vamos sim" },
        { dir: "in", type: "deleted", time: "18:57", text: "Mensagem apagada pelo remetente" },
        { dir: "in", type: "deleted", time: "18:57", text: "Mensagem apagada pelo remetente" },
        { type: "day", date: "2023-12-26" },
        { dir: "in", type: "text", time: "10:21", text: "Opa" },
        { dir: "in", type: "text", time: "10:21", text: "Chegando" },
        { dir: "out", type: "text", time: "10:24", text: "Opa" },
        { dir: "out", type: "text", time: "10:24", text: "Tambem" },
        { dir: "out", type: "text", time: "10:24", text: "5 min" },
        { dir: "out", type: "text", time: "10:33", text: "Mesmo esquema entrar na garagem correto" },
        { dir: "out", type: "text", time: "10:33", text: "To aqui" },
        { dir: "in", type: "text", time: "11:43", text: "Contato\nAlexandre de Moraes BRASILIA\n+55 61 99266-4093\nNovo\n+55 61 99266-4093\nSTF TSE NOVO\n+55 61 99266-4093\nEu STF\n+55 61 99266-4093" },
        { type: "day", date: "2023-12-27" },
        { dir: "in", type: "text", time: "19:41", text: "Pode ser dia 30 o almoço?" },
        { dir: "in", type: "text", time: "19:41", text: "Irmão" },
        { dir: "in", type: "text", time: "19:41", text: "Alex quer ir almoçar lá no dia 30" },
        { dir: "out", type: "text", time: "19:46", text: "Pode!" },
        { dir: "in", type: "text", time: "19:47", text: "Confirmei" },
        { dir: "in", type: "text", time: "19:47", text: "Depois passa o endereço de lá e o cel de quem ele procura" },
        { dir: "in", type: "text", time: "19:47", text: "Sao 9 pessoas e 4 segurancas (veja algo para eles)" },
        { dir: "in", type: "text", time: "19:49", text: "Passe o endereco certo para eu enviar para a escolta" },
        { dir: "out", type: "text", time: "20:54", text: "Localização\nSix Senses Botanique\nRua Elidio Gonçalves da Silva, 4000\nCampos Do Jordao SP\n12460-000\nBrazil" },
        { dir: "in", type: "text", time: "21:15", text: "A casa fica no mesmo endereço?\nPrecisa de um contato pq vai a escolta 1 dia antes" },
        { dir: "out", type: "text", time: "22:38", text: "Contato\nThatiane Prime\n+55 11 95742-4509" },
        { type: "day", date: "2024-01-12" },
        { dir: "in", type: "text", time: "14:57", text: "Irmao, pode falar aí?\nVou jaja no 👨" },
        { type: "day", date: "2024-01-15" },
        { dir: "in", type: "text", time: "17:38", text: "Respondeu a Vivi?" },
        { dir: "out", type: "text", time: "17:40", text: "Era isso que te chamei" },
        { dir: "out", type: "text", time: "17:40", text: "Vc fechou 3 anos?" },
        { dir: "in", type: "text", time: "17:40", text: "4 anos" },
        { dir: "in", type: "text", time: "17:44", text: "Mas pode fazer 3" },
        { dir: "in", type: "text", time: "17:44", text: "Sem problemas" },
        { type: "day", date: "2024-01-17" },
        { dir: "in", type: "text", time: "20:47", text: "Fala pra Patroa aí que o Careca confirmou o jantar com a gente no dia 02/02.\nOs 3 casais" },
        { dir: "out", type: "text", time: "21:04", text: "Boaa" },
        { type: "day", date: "2024-01-23" },
        { dir: "in", type: "text", time: "07:04", text: "Sexta-feira dia 02 temos jantar com o Alex" },
        { dir: "in", type: "text", time: "07:04", text: "E as esposas" },
        { dir: "in", type: "text", time: "07:05", text: "Bom que ela já vai conhecer Patricia e a Vivi" },
        { type: "day", date: "2024-01-30" },
        { dir: "in", type: "text", time: "08:52", text: "Bom dia" },
        { dir: "in", type: "text", time: "08:52", text: "Confirmada amanhã em Brasília?" },
        { dir: "in", type: "text", time: "08:52", text: "Acho melhor fazer na sua casa pode ser? Estou sem ninguém até fevereiro rsrs" },
        { dir: "in", type: "text", time: "08:52", text: "Ferrou nosso after amanhã" },
        { dir: "in", type: "text", time: "08:52", text: "Alex pediu pra ser lá em casa" },
        { dir: "in", type: "text", time: "08:53", text: "Só se mandar uma turma ir jantar fora e vai la depois das 23" },
        { dir: "in", type: "text", time: "08:53", text: "Tinha pego a cantora pra ir aquecendo a turma. Pqp" },
        { dir: "out", type: "text", time: "09:11", text: "Kkk" },
        { dir: "out", type: "text", time: "09:11", text: "Melhor nao" },
        { dir: "in", type: "text", time: "09:14", text: "Vamos focar na reunião né!\nMarquei lá em casa 19:30" },
        { type: "day", date: "2024-01-31" },
        { dir: "out", type: "text", time: "16:29", text: "Me manda endereco" },
        { dir: "in", type: "text", time: "16:30", text: "https://maps.app.goo.gl/Su88jvyxcnpwqCyh9?g_st=iwb\n[Residencial Boa Vista · 4.2★(5) · Complexo de condomínio]\nConj, Smdb Conjunto 26, 8 - St. Hab Ind Sul, Brasília - DF, 71680-260\nAqui" },
        { dir: "out", type: "text", time: "16:30", text: "Nao ta aparecendo" },
        { dir: "out", type: "text", time: "16:30", text: "O endereco" },
        { dir: "in", type: "text", time: "16:30", text: "https://maps.app.goo.gl/Su88jvyxcnpwqCyh9?g_st=iwb\n[Residencial Boa Vista · 4.2★(5) · Complexo de condomínio]\nConj, Smdb Conjunto 26, 8 - St. Hab Ind Sul, Brasília - DF, 71680-260" },
        { dir: "in", type: "text", time: "16:42", text: "SMDB 26, Lote 08, Casa F" },
        { dir: "in", type: "text", time: "16:42", text: "Residencial Boa Vista" },
        { type: "day", date: "2024-03-15" },
        { dir: "in", type: "text", time: "14:58", text: "Irmao" },
        { dir: "in", type: "text", time: "14:58", text: "Depois vê ai que preciso retornar o careca" },
        { dir: "out", type: "text", time: "15:06", text: "O contato não é o fabiano" },
        { dir: "out", type: "text", time: "15:06", text: "É o angelo do banco" },
        { dir: "out", type: "text", time: "15:06", text: "Nao consigo atender agora" },
        { dir: "out", type: "text", time: "15:07", text: "Te chamo daqui a pouco" },
        { dir: "in", type: "text", time: "15:07", text: "Tá" },
        { dir: "in", type: "text", time: "15:07", text: "Manda pagar a ele" },
        { dir: "in", type: "text", time: "15:07", text: "O careca não pode atrasar" },
        { dir: "in", type: "text", time: "15:07", text: "Passa o contato do Ângelo que passo pra ele" },
        { dir: "out", type: "text", time: "15:08", text: "Contato\nAngelo Silva\n+55 11 99266-8146" },
        { dir: "in", type: "text", time: "15:09", text: "Passei pra ele" },
        { dir: "in", type: "text", time: "15:09", text: "Avisa que vão ligar do escritório" },
        { type: "day", date: "2024-04-03" },
        { dir: "in", type: "text", time: "—", text: "O que acha de eu convidar o DPF Andrei" },
        { dir: "in", type: "text", time: "—", text: "Aí fechamos o PGR e o DPF" },
        { dir: "in", type: "text", time: "—", text: "Acho ótimo" },
        { dir: "in", type: "text", time: "—", text: "Pode convidar" },
        { dir: "in", type: "text", time: "—", text: "Podem entrar em contato lá na PF. Ele aceitou" },
        { dir: "in", type: "text", time: "—", text: "Vc avisa pro Marcio entrar em contato com o Andrei?" },
        { dir: "in", type: "text", time: "—", text: "Seu amigo Esteves vai dar pulos de raiva" },
        { dir: "in", type: "text", time: "—", text: "Marcio fazer o convite formal ao delegado geral" },
        { dir: "out", type: "text", time: "—", text: "Vai fazer agora" }
      ]
    },
    {
      id: "gustavo",
      name: "Gustavo Motorista",
      phone: "5511942328664",
      avatar: "assets/avatars/gustavo-motorista.png",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2023-12-21" },
        { dir: "out", type: "text", time: "08:16", text: "Descendo" },
        { dir: "out", type: "text", time: "10:42", text: "Modelo e placa nosso carro" },
        { dir: "in", type: "text", time: "10:42", text: "Range Rover Vogue\nRSB7C37" },
        { dir: "out", type: "text", time: "10:46", text: "Tucumã 99" },
        { dir: "out", type: "text", time: "10:46", text: "Descendo" },
        { dir: "out", type: "text", time: "10:46", text: "Vamos nesse endereco agora" }
      ]
    },
    {
      id: "thatiane",
      name: "Thatiane Prime",
      phone: "5511957424509",
      avatar: "assets/avatars/thatiane-prime.png",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2023-12-27" },
        { dir: "out", type: "text", time: "19:47", text: "Oi" },
        { dir: "out", type: "text", time: "19:47", text: "Dia 30 vou precisar fazer um almoco em campos" },
        { dir: "out", type: "text", time: "19:47", text: "Para convidados" },
        { dir: "out", type: "text", time: "19:47", text: "Ze maria" },
        { dir: "out", type: "text", time: "19:47", text: "Preciso que michael vai pra la" },
        { dir: "out", type: "text", time: "19:47", text: "Tem que ser experiencia completa" },
        { dir: "out", type: "text", time: "19:47", text: "Convidados ultra vips" },
        { dir: "out", type: "text", time: "19:48", text: "9 paxs e 4 segurancas" },
        { dir: "in", type: "text", time: "20:50", text: "Boa noite! Vamos providenciar" },
        { dir: "in", type: "text", time: "20:52", text: "Eles vão ao Botanique também ou só Pix?" },
        { dir: "in", type: "text", time: "20:52", text: "Devo providenciar cantor?" },
        { dir: "out", type: "text", time: "20:52", text: "Sim" },
        { dir: "out", type: "text", time: "20:52", text: "Aquele" },
        { dir: "out", type: "text", time: "20:52", text: "E fazer uma experiencia no botanique" },
        { dir: "out", type: "text", time: "20:52", text: "Deixar cavalos etc" },
        { dir: "in", type: "text", time: "20:54", text: "Combinado! Vamos providenciar de acordo" },
        { type: "day", date: "2025-08-21" },
        { dir: "out", type: "text", time: "—", text: "Nao deixe de atender barci" }
      ]
    },
    {
      id: "michael",
      name: "Michael",
      phone: "5511956599130",
      avatar: "assets/avatars/michael.png",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2023-12-30" },
        { dir: "out", type: "text", time: "13:30", text: "Marcou experiencia hotel?" },
        { dir: "out", type: "text", time: "13:30", text: "Me avisa quando chegarem" },
        { dir: "in", type: "text", time: "13:34", text: "Chegou tô apresentando" },
        { dir: "in", type: "text", time: "13:34", text: "A casa" },
        { dir: "out", type: "text", time: "13:35", text: "Nao precisa ficar indo em todos locais dentro dacasa pra nao ficar forçado demais. Deixa ser bem natural" },
        { dir: "out", type: "text", time: "13:35", text: "Vai me dando noticias" },
        { dir: "in", type: "text", time: "14:43", text: "O Airton desembargador veio de táxi. Oq vc acha de eu manda Álvaro leva ele no nosso carro e libera táxi oferecer mais conforto" },
        { dir: "out", type: "text", time: "15:01", text: "No final correto?" },
        { dir: "in", type: "text", time: "15:02", text: "Isso" },
        { dir: "out", type: "text", time: "15:02", text: "Claro" },
        { dir: "in", type: "text", time: "19:22", text: "Zé Maria tirou foto com o ministro e trocou telefone e chamou no WhatsApp agradecendo.\nSó para seu conhecimento mesmo" },
        { dir: "out", type: "text", time: "19:24", text: "Isso nao podia ne" },
        { dir: "out", type: "text", time: "19:24", text: "Fale com ele pra mim que eu nao vou gostar disso" },
        { dir: "in", type: "text", time: "19:26", text: "Na hora eu não consegui intervir, porque o ministro pediu para tirar fotos com todos , porém eu falei que não podia porque a empresa não permite.\nO ze e o ajudante dele tirou" },
        { dir: "in", type: "text", time: "19:27", text: "Zé me chamou de canto e falou que não podia falar não para o ministro, e eu expliqei que o senhor não gostava" },
        { dir: "out", type: "text", time: "19:28", text: "Mas se foi o ministro que pediu tudo bem" }
      ]
    },
    {
      id: "vivi",
      name: "Vivi Moraes",
      phone: "5511983445794",
      avatar: "assets/avatars/viviane.jpg",
      tags: ["contrato", "moraes"],
      messages: [
        { type: "day", date: "2024-01-11" },
        { type: "system", time: "16:53", text: "As mensagens e chamadas desta conversa estão protegidas com a criptografia de ponta a ponta. Toque para mais informações." },
        { type: "system", time: "16:53", text: "Vivi Moraes foi adicionado à sua lista de contatos." },
        { dir: "in", type: "text", time: "16:48", text: "Prezado Daniel, boa tarde. Conforme conversamos, estou enviando minuta de contrato de prestação de serviços para sua análise.\nEstou a disposição para qualquer esclarecimento.\nAbraço\nViviane Barci de Moraes" },
        { dir: "in", type: "doc", time: "16:49", name: "MINUTA DE CONTRATO", sub: "Autor: Guilherme Benazzi · Última modificação: Ministro Alexandre de Moraes 11/01/2024 16:30" },
        { dir: "out", type: "text", time: "17:23", text: "Ok, muito obrigado!" },
        { type: "day", date: "2024-01-15" },
        { dir: "out", type: "doc", time: "21:22", name: "MINUTA CONTRATO - Marcas Revisao", sub: "Última modificação: Leonardo Palhares" },
        { dir: "out", type: "text", time: "21:25", text: "Boa Noite!\nSegue o documento preenchido! Foi incluido apenas a cláusula I.3. Por favor, nos indique se está adequada.\nCaso estejam de acordo, combinamos a assinatura!\nUm abraço" },
        { dir: "in", type: "text", time: "22:01", text: "Boa noite. Na cláusula I.3 somente alterarei “sócios e acionistas controladores da CONTRATADA” para “do CONTRATANTE”. Ok?\nMas como combinado será incluído.\nIrei colocar a data do documento e podemos assinar.\nPode ser digitalmente se preferir.\nAbraço" },
        { type: "day", date: "2024-01-17" },
        { dir: "in", type: "text", time: "10:09", text: "Bom dia!\nSegue a minuta do contrato.\nAbraço" },
        { dir: "in", type: "doc", time: "10:10", name: "MINUTA CONTRATO BANCO MASTER FINAL", sub: "36 parcelas mensais de R$ 3.000.000,00 líquidos" }
      ]
    },
    {
      id: "fabiano",
      name: "Fabiano Zettel 1",
      phone: "5511932611111",
      avatar: "assets/avatars/fabiano-zettel.png",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2024-02-08" },
        { dir: "out", type: "text", time: "12:20", text: "Me manda contrato barci moraes assinado?" },
        { dir: "out", type: "text", time: "12:21", text: "Quando era o primeiro pgto?" },
        { dir: "in", type: "doc", time: "12:25", name: "BARCI DE MORAES - CONTRATOBANCOMASTER_FINAL", sub: "Anexo" },
        { dir: "in", type: "text", time: "12:26", text: "Até o 5 dia util." },
        { dir: "out", type: "text", time: "12:26", text: "Entao ja passou" },
        { dir: "out", type: "text", time: "12:27", text: "Nao foi pago?" },
        { dir: "in", type: "text", time: "12:27", text: "Ontem, no caso." },
        { dir: "out", type: "text", time: "12:27", text: "Qual os dados da conta" },
        { dir: "in", type: "text", time: "12:27", text: "Vou pegar." },
        { dir: "in", type: "text", time: "12:27", text: "É o Banco que paga." },
        { dir: "in", type: "text", time: "12:28", text: "Banco Itaú S.A,\nnº 05760-0,\nagência 2000" },
        { dir: "out", type: "text", time: "12:28", text: "Confirma c angelo se nao foi pago" },
        { dir: "in", type: "text", time: "12:28", text: "Agora." },
        { dir: "in", type: "text", time: "12:44", text: "Ta no fluxo de pagamento para hj." }
      ]
    },
    {
      id: "angelo",
      name: "Angelo Silva",
      phone: "5511992668146",
      avatar: "assets/avatars/angelo-silva.png",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2024-02-08" },
        { dir: "out", type: "text", time: "20:17", text: "Pagou aquele contrato 3mm" },
        { dir: "out", type: "text", time: "20:17", text: "?" },
        { dir: "in", type: "doc", time: "20:37", name: "BARCI DE MORAES SOCIEDADE DE ADVOGA.pdf", sub: "Recibo STR0007 · R$ 3.422.268,14" },
        { dir: "in", type: "text", time: "20:38", text: "Este q o Fabiano me passou mais cedo … sim.." },
        { type: "day", date: "2024-03-15" },
        { dir: "out", type: "text", time: "15:05", text: "Angelo" },
        { dir: "out", type: "text", time: "15:05", text: "Pqp" },
        { dir: "out", type: "text", time: "15:05", text: "Nao pagaram barci de moraes" },
        { dir: "out", type: "text", time: "15:05", text: "Nao to entendendo isso" },
        { dir: "out", type: "text", time: "15:05", text: "Contrato mais importantw que temos" },
        { dir: "out", type: "text", time: "15:06", text: "Te pedi pra nao falhar" },
        { dir: "out", type: "text", time: "15:06", text: "Surreal" },
        { dir: "out", type: "text", time: "15:06", text: "Vamos ter problemas" },
        { dir: "in", type: "text", time: "15:06", text: "Pagamento" },
        { dir: "in", type: "text", time: "15:06", text: "ADV?" },
        { dir: "in", type: "text", time: "15:06", text: "Vou checar…" },
        { dir: "out", type: "text", time: "15:06", text: "Manda pagar agora" },
        { dir: "out", type: "text", time: "15:11", text: "Paga urgente" },
        { dir: "in", type: "text", time: "15:12", text: "Sim… já está liquidando…" },
        { dir: "out", type: "text", time: "15:17", text: "Me manda comprovante" },
        { dir: "in", type: "text", time: "15:17", text: "Um minuto q estão na tesouraria liquidando" },
        { dir: "in", type: "text", time: "15:21", text: "Tá pago… um minuto te mando o comprovante…" },
        { dir: "in", type: "doc", time: "15:22", name: "barci", sub: "Anexo" },
        { dir: "in", type: "text", time: "15:23", text: "Vamos pagar antecipado e depois pegamos a NF… já está orientado" },
        { type: "day", date: "2025-04-01" },
        { dir: "out", type: "text", time: "21:29", text: "Oi" },
        { dir: "out", type: "text", time: "21:29", text: "Contrato barci de moraes" },
        { dir: "out", type: "text", time: "21:29", text: "Ta onde?" },
        { dir: "out", type: "text", time: "21:29", text: "E algo que pessoal tem acesso" },
        { dir: "in", type: "text", time: "23:13", text: "Tenho q ver…" },
        { dir: "in", type: "text", time: "23:13", text: "O q precisa?" },
        { dir: "out", type: "text", time: "23:13", text: "Ninguem ter acesso" },
        { dir: "out", type: "text", time: "23:13", text: "Vc pegar e nao deixar ninguem ter acesso a isso" },
        { dir: "in", type: "text", time: "23:14", text: "Ok. Vou localizar amanhã." }
      ]
    },
    {
      id: "romy",
      name: "Romy Banco Master",
      phone: "5511914794467",
      avatar: "assets/avatars/romy-banco-master.png",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2024-03-15" },
        { dir: "out", type: "text", time: "15:17", text: "Romy esse barci moraes por favor nao deixe atrasar um dia, coloca no seu controle" },
        { dir: "out", type: "text", time: "15:17", text: "E o pgto mais importante que temos" },
        { dir: "in", type: "text", time: "15:18", text: "pode deixar, estou fazendo direto por aqui" },
        { dir: "in", type: "text", time: "15:18", text: "neste instante" },
        { dir: "out", type: "text", time: "15:18", text: "Mas todo mês acompanha isso pra mim" },
        { dir: "out", type: "text", time: "15:19", text: "Pode pagar sempre, sem nota" },
        { dir: "out", type: "text", time: "15:19", text: "Do jeito que for" },
        { dir: "in", type: "text", time: "15:19", text: "Ok" },
        { dir: "in", type: "doc", time: "15:21", name: "barci.pdf", sub: "Anexo" }
      ]
    },
    {
      id: "alberto",
      name: "Alberto Felix de Oliveira Neto",
      phone: "5511994881612",
      avatar: "assets/avatars/alberto-felix.png",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2025-07-14" },
        { dir: "in", type: "text", time: "16:49", text: "Temos 40mm de contas a pagar pendentes, que seguramos semana passada" },
        { dir: "in", type: "text", time: "16:49", text: "Podemos pagar uns 15mm hoje para nao acumular?" },
        { dir: "out", type: "text", time: "16:50", text: "O que e" },
        { dir: "out", type: "text", time: "16:54", text: "Paga 15 e inclui o barci moraes" },
        { dir: "in", type: "text", time: "16:54", text: "Pagamos barci hj" },
        { dir: "in", type: "text", time: "16:54", text: "Ok" },
        { type: "day", date: "2025-10-01" },
        { dir: "in", type: "text", time: "21:01", text: "Ok" },
        { dir: "in", type: "text", time: "21:35", text: "Chegou btg\nPagamsos metropoles e barci" },
        { dir: "out", type: "text", time: "21:42", text: "Mas nao faz barci pix ne" },
        { dir: "out", type: "text", time: "21:42", text: "Fez?" },
        { dir: "in", type: "text", time: "21:42", text: "Fez, nao pode?" },
        { dir: "in", type: "text", time: "21:44", text: "Foi pix para os mesmos dados da ted" },
        { dir: "out", type: "text", time: "21:46", text: "Nao e bom" }
      ]
    },
    {
      id: "palhares",
      name: "Leonardo Palhares",
      phone: "",
      avatar: "assets/avatars/leonardo-palhares.png",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2025-05-16" },
        { dir: "in", type: "text", time: "—", text: "duas minutas para vc escolher o deal" },
        { dir: "out", type: "text", time: "—", text: "Opcao 1 não é o negocio" },
        { dir: "out", type: "text", time: "—", text: "Os ativos sao deles...ja" },
        { type: "day", date: "2025-05-19" },
        { dir: "in", type: "text", time: "—", text: "escritório deles não pode ser parte do contrato, não pode ter participação em empresas" },
        { dir: "in", type: "text", time: "—", text: "Ele queria que escritório fosse dono direto da cota, sem ser sócio das SPEs" },
        { type: "day", date: "2025-07-16" },
        { dir: "in", type: "text", time: "—", text: "A gente precisa iniciar o fluxo de pagamentos do escritório Biaci" },
        { dir: "out", type: "text", time: "—", text: "num volume maior" },
        { dir: "out", type: "text", time: "—", text: "Faz urgente" },
        { type: "day", date: "2025-07-24" },
        { dir: "out", type: "text", time: "—", text: "ta trocando contrato barco?" },
        { dir: "out", type: "text", time: "—", text: "Barci" },
        { dir: "in", type: "text", time: "—", text: "Eles queriam que a empresa que fosse dona do ativo fosse uma que os sócios estão muito visíveis e haveria risco reputacional grande" },
        { dir: "in", type: "text", time: "—", text: "O Guilherme está conferindo com a chefe dele se vão adotar uma estrutura diferente para a propriedade dos ativos ou não" }
      ]
    },
    {
      id: "marcos",
      name: "Marcos Prime",
      phone: "5511988101010",
      initials: "MP",
      color: "#128c7e",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2025-07-16" },
        { dir: "out", type: "text", time: "—", text: "ja era pra ter resolvido" },
        { dir: "out", type: "text", time: "—", text: "Eles nao estao usando" },
        { dir: "in", type: "text", time: "—", text: "terá mudança de empresa" },
        { dir: "in", type: "text", time: "—", text: "não será mais a Barci" },
        { dir: "in", type: "text", time: "—", text: "Já usaram aviões e helicópteros" },
        { dir: "in", type: "text", time: "—", text: "devido mudança de contrato de Barci para a outra empresa deles Lux" },
        { dir: "in", type: "text", time: "—", text: "estão gostando da utilização das cotas de vcs" },
        { dir: "in", type: "text", time: "—", text: "Sim, estamos gostando muito" }
      ]
    },
    {
      id: "ana-claudia",
      name: "Ana Claudia Financeiro1",
      phone: "553183288156",
      initials: "AC",
      color: "#e67e22",
      tags: ["contrato"],
      messages: [
        { type: "day", date: "2025-07-24" },
        { dir: "in", type: "text", time: "—", text: "está pedindo para pagar" }
      ]
    },
    {
      id: "marcio",
      name: "Marcio Conjur",
      phone: "5511999824806",
      avatar: "assets/avatars/marcio-conjur.png",
      tags: ["londres"],
      messages: [
        { type: "day", date: "2024-04-03" },
        { dir: "out", type: "text", time: "—", text: "Ministro fez convite ao andrei PF" },
        { dir: "in", type: "text", time: "—", text: "ótimo" },
        { dir: "in", type: "text", time: "—", text: "interesse em participar do evento em Londres" },
        { dir: "in", type: "text", time: "—", text: "algum custo (hospedagem, passagem) é coberto pelos organizadores?" },
        { dir: "in", type: "text", time: "—", text: "Todas as despesas bancadas por nós" }
      ]
    },
    {
      id: "leo",
      name: "Leo Serrano Giunchetti",
      phone: "5511969204644",
      avatar: "assets/avatars/leo-serrano.png",
      tags: ["londres"],
      messages: [
        { type: "day", date: "2024-04-10" },
        { dir: "in", type: "text", time: "—", text: "mais sensiveis" },
        { dir: "in", type: "text", time: "—", text: "Alexandre, Toffoli, etc" }
      ]
    },
    {
      id: "renno",
      name: "Luiz Rennó",
      phone: "553186058949",
      initials: "LR",
      color: "#8e44ad",
      tags: ["londres"],
      messages: [
        { type: "day", date: "2024-04-19" },
        { dir: "out", type: "text", time: "—", text: "evento super exclusivo com alexandre de moraes em londres" }
      ]
    },
    {
      id: "ana",
      name: "Ana Matos Mkt",
      phone: "5511943290909",
      avatar: "assets/avatars/ana-matos.png",
      tags: ["londres", "moraes"],
      messages: [
        { type: "day", date: "2025-07-10" },
        { dir: "in", type: "text", time: "—", text: "O Andrei PF precisa de um Convite formal para aceitar Londres" },
        { dir: "in", type: "text", time: "—", text: "Grupo Voto pode mandar dele e demais?" },
        { dir: "out", type: "text", time: "—", text: "Pode" },
        { type: "day", date: "2025-07-18" },
        { dir: "out", type: "text", time: "—", text: "De jeito nenhum" },
        { dir: "out", type: "text", time: "—", text: "Alexandre morre se vc fizer isso" },
        { type: "day", date: "2025-07-21" },
        { dir: "out", type: "text", time: "—", text: "reclamou MUITO do evento" },
        { type: "day", date: "2025-07-22" },
        { dir: "in", type: "text", time: "—", text: "o dia aqui com Vivi Moraes e o ministro fechando o programa do evento" }
      ]
    },
    {
      id: "ciro",
      name: "Ciro Soares",
      phone: "557181533776",
      avatar: "assets/avatars/ciro-soares.png",
      tags: ["londres"],
      messages: [
        { type: "day", date: "2024-04-14" },
        { dir: "in", type: "text", time: "13:06", text: "Amizade é tudo viu Irmão" },
        { dir: "in", type: "text", time: "13:06", text: "Gonet é firme" },
        { dir: "in", type: "text", time: "13:07", text: "Leia isso aqui!!!!" },
        { dir: "in", type: "text", time: "13:07", text: "Fique só com vc" },
        { dir: "in", type: "text", time: "13:07", text: "Querido amigo Georges, queridas Luciana e Elaine, estimado PGR Dr. Gonet , caros Colegas Procuradores Gerais, bom dia!\n\nRecebo com enorme satisfação e alegria o gesto grandioso do colega e amigo Georges, que sempre esteve solícito a todos nós, nas horas mais difíceis e estratégicas. O MPDFT tem nos dado grandes nomes.\n\nA ele a minha gratidão e reconhecimento. Deixarei as palavras mais devidas para quarta-feira.\n\nSaiba que terão um presidente incansável nestes sete meses de presidência.\n\nRecebo também todo apoio dos PGJs , que tive, como um ato de generosidade a um insistente candidato , mas também como um reconhecimento aos meus 35 anos de dedicação à nossa Instituição, à qual sempre fui um Leal soldado.\n\nTrabalharemos juntos no colegiado, agora prestigiadíssimo com a presença mais próxima do PGR Dr. Gonet. Ele trouxe luz e esperanças ao MP brasileiro.\n\nAgradeço ao Presidente César e a cada PGJ, ao PGR e ao PGT.\n\nA sabedoria mineira ensina que devemos sempre nos apegar ao que nos une, não ao que nos separa. E o que mais nos une é o presente e o futuro da Instituição. Ao MP todos as nossas forças.\n\nAvante!!" },
        { dir: "in", type: "text", time: "13:08", text: "Jarbas escreveu" },
        { dir: "out", type: "text", time: "13:08", text: "O cara largou?" },
        { dir: "in", type: "text", time: "13:08", text: "Sim" },
        { dir: "out", type: "text", time: "13:09", text: "Top demais" },
        { dir: "in", type: "audio", time: "13:09", duration: "—", transcript: "Cara, eu pedi o Gonet ontem, ele me ligou falar um assunto, aí eu falei, Gonet, pede o cara para tirar a candidatura, pede o cara que o cara vai tomar uma porrada arretada. Aí o Gonet me ligou ontem à noite e falou: Ciro, acabei de ligar para ele, ele vai desistir." },
        { type: "day", date: "2025-03-15" },
        { dir: "in", type: "text", time: "—", text: "Liga aqui" },
        { dir: "in", type: "text", time: "—", text: "Ele quer falar com você" },
        { type: "day", date: "2025-03-28" },
        { dir: "in", type: "text", time: "—", text: "Que bom! Estou na torcida por vocês!" },
        { dir: "in", type: "text", time: "—", text: "Já estou com saudades de você! Estou embarcando para Roma." },
        { dir: "in", type: "text", time: "—", text: "Manda essa mensagem para ele" },
        { dir: "in", type: "text", time: "—", text: "Lhe adora" },
        { dir: "in", type: "text", time: "—", text: "Ele vai para Londres com a gente" },
        { dir: "in", type: "text", time: "—", text: "Oba!!! Tomara que tenha charuto e macalan!" },
        { type: "day", date: "2025-03-29" },
        { dir: "in", type: "text", time: "—", text: "Gonet perguntou se o filho dele pode ir com a gente para Londres" },
        { dir: "out", type: "text", time: "—", text: "Obvio ne" },
        { dir: "in", type: "text", time: "—", text: "Você é uma máquina" },
        { dir: "in", type: "text", time: "—", text: "Gonet mandou" },
        { type: "day", date: "2025-04-07" },
        { dir: "in", type: "text", time: "—", text: "Preciso falar com vc" },
        { dir: "in", type: "text", time: "—", text: "Estou indo no PG agora" },
        { type: "day", date: "2025-06-19" },
        { dir: "in", type: "text", time: "—", text: "PG confirmou a ida pra Londres" },
        { dir: "in", type: "text", time: "—", text: "Pedrinho filho do PG pode ir com a gente" }
      ]
    },
    {
      id: "martha",
      name: "Martha Graeff",
      phone: "",
      initials: "MG",
      color: "#c0392b",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2025-03-19" },
        { dir: "out", type: "text", time: "20:23", text: "estou com o Ministro" },
        { type: "day", date: "2025-03-20" },
        { dir: "in", type: "text", time: "00:32", text: "está com gente aí?" },
        { dir: "out", type: "text", time: "00:32", text: "acabou chegando hugo e ciro aqui pra falarem com Alexandre" },
        { type: "day", date: "2025-04-19" },
        { dir: "out", type: "text", time: "—", text: "indo encontrar alexandre moraes aqui perto de casa" },
        { dir: "in", type: "text", time: "—", text: "está em Campos" },
        { dir: "out", type: "text", time: "—", text: "Ele ta passando feriado" },
        { type: "day", date: "2025-04-29" },
        { dir: "in", type: "text", time: "—", text: "Quem era o primeiro cara?" },
        { dir: "out", type: "text", time: "—", text: "alexandre moraes" },
        { type: "day", date: "2025-05-21" },
        { dir: "out", type: "text", time: "—", text: "Ciro e alexandre" },
        { type: "day", date: "2025-05-26" },
        { dir: "out", type: "text", time: "—", text: "marcando jantar com as mulheres fabio e dele" },
        { type: "day", date: "2025-08-08" },
        { dir: "out", type: "text", time: "—", text: "Com ciro" }
      ]
    },
    {
      id: "stella",
      name: "Stella",
      phone: "",
      initials: "ST",
      color: "#16a085",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2024-11-15" },
        { dir: "out", type: "text", time: "—", text: "com alexandre moraes" }
      ]
    },
    {
      id: "sidney",
      name: "Motorista Brasilia Sidney",
      phone: "556198436116",
      initials: "MS",
      color: "#7f8c8d",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2024-11-15" },
        { dir: "in", type: "text", time: "—", text: "Min Alexandre chegou" }
      ]
    },
    {
      id: "paulo-sergio",
      name: "Paulo Sergio",
      phone: "",
      initials: "PS",
      color: "#2980b9",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2025-03-19" },
        { dir: "out", type: "text", time: "—", text: "com Moraes aqui" }
      ]
    },
    {
      id: "ph-brb",
      name: "PAULO HENRIQUE PH BRB",
      phone: "",
      initials: "PH",
      color: "#1a73e8",
      tags: ["moraes"],
      messages: [
        { type: "day", date: "2025-11-16" },
        { dir: "out", type: "text", time: "13:40", text: "tudo bem?" }
      ]
    }
  ]
};
